version: '3.2'

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: alert-error-log
    volumes: 
      - ./:/app
    ports:
      - "4000:4000"
   
